<?php
require_once 'includes/db.php';

$token = $_GET['token'] ?? '';

if (!$token) {
    die("<h2 style='color:red;text-align:center'>Invalid verification link</h2>");
}

$stmt = $pdo->prepare("SELECT * FROM report_verifications WHERE token = ?");
$stmt->execute([$token]);
$report = $stmt->fetch(PDO::FETCH_ASSOC);

// log view
$ip = $_SERVER['REMOTE_ADDR'] ?? 'UNKNOWN';
$pdo->prepare("INSERT INTO verification_logs (token, ip_address, verified_at)
               VALUES (?, ?, NOW())")
    ->execute([$token, $ip]);
?>
<!DOCTYPE html>
<html>
<head>
<title>Receipt Verification - Nexus Bank</title>
<style>
body{
    background:#0b1020;
    font-family:Segoe UI, sans-serif;
    display:flex;
    align-items:center;
    justify-content:center;
    height:100vh;
    color:#e5e7eb;
}
.card{
    background:#020617;
    padding:40px;
    border-radius:16px;
    width:420px;
    text-align:center;
    box-shadow:0 0 30px rgba(99,102,241,.45);
}
.ok{color:#22c55e;font-size:22px}
.bad{color:#ef4444;font-size:22px}
.small{color:#94a3b8;font-size:13px}
hr{border-color:#1e293b;margin:15px 0}


</style>
</head>
<body>

<div class="card">
<?php if($report): ?>
    <div class="ok">✔ Receipt Verified</div>
    <hr>
    <p><b>Report Type:</b> <?= htmlspecialchars($report['report_type']) ?></p>
    <p><b>Generated By Admin ID:</b> <?= $report['admin_id'] ?></p>
    <p><b>Generated On:</b> <?= $report['created_at'] ?></p>
<?php else: ?>
    <div class="bad">✖ Invalid or Fake Receipt</div>
<?php endif; ?>

<p class="small">Nexus Bank Secure Verification System</p>
</div>

</body>
</html>
